name: prompts
version: 1.3.1
description: Rich, simple, synchronous command-line prompt library for Dart.
homepage: https://github.com/thosakwe/prompts
author: Tobe O <thosakwe@gmail.com>
environment:
  sdk: ">=2.0.0 <3.0.0"
dependencies:
  charcode: ^1.0.0
  io: ^0.3.2
dev_dependencies:
  pedantic: ^1.0.0
