name: prompts
version: 2.0.0
description: Rich, simple, synchronous command-line prompt library for Dart.
homepage: https://github.com/thosakwe/prompts
environment:
  sdk: '>=3.0.0'
dependencies:
  charcode: 1.4.0
  io: 1.0.5
